using Bogus;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Taxi.Web.Data.Entities;

namespace Taxi.Web.Data
{
    public class SeedDb
    {
        private readonly DataContext _datacontext;

        public SeedDb(DataContext dataContext)
        {
            this._datacontext = dataContext;
        }

        public async Task SeedAsync()
        {
            await _datacontext.Database.EnsureCreatedAsync();
            await CheckTaxiAsync();

        }

        private async Task CheckTaxiAsync()
        {
            if (_datacontext.Taxis.Any())
            {
                return;
            }

            //TODO: Poblate with autogenerated Data - Testing Data
            Faker<TripEntity> tripFaker = new Faker<TripEntity>()
                .RuleFor(x => x.SourceLongitude, f => f.Address.Longitude(-90,-89))
                .RuleFor(x => x.SourceLatitude, f => f.Address.Latitude(13,14))
                .RuleFor(x => x.Source, f => f.Address.StreetAddress())
                .RuleFor(x => x.StartDate, f => f.Date.Between(DateTime.UtcNow, DateTime.UtcNow.AddMinutes(5)))
                .RuleFor(x => x.EndDate, f => f.Date.Between(DateTime.UtcNow.AddMinutes(5), DateTime.UtcNow.AddMinutes(10)))
                .RuleFor(x => x.Qualification, f => f.Random.Float() * 10)
                .RuleFor(x => x.Remarks, f => f.Lorem.Slug());

            Faker<TaxiEntity> taxiFaker = new Faker<TaxiEntity>()
                .RuleFor(x => x.Plaque, f => f.Random.AlphaNumeric(6).ToUpper());

            TaxiEntity taxi;
            for (int i = 0; i < 5; i++)
            {
                do //till it gets a unique Plaque, in case it already exist on DB
                {
                     taxi= taxiFaker.Generate();
                } while (_datacontext.Taxis.FirstOrDefault(t=>t.Plaque == taxi.Plaque) != default(TaxiEntity));

                taxi.Trips = new List<TripEntity>();
                for (int j = 0; j < 5; j++)
                {
                    taxi.Trips.Add(tripFaker.Generate());
                }
                _datacontext.Taxis.Add(taxi);
            }
            await _datacontext.SaveChangesAsync();
        }
    }
}
